// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8L4vZX9mGOkmZQEPfnuy3v3c7orXCqM',
    appId: '1:551736633719:web:3b30db4fdc4c90927c9972',
    messagingSenderId: '551736633719',
    projectId: 'biovolt',
    authDomain: 'biovolt.firebaseapp.com',
    storageBucket: 'biovolt.firebasestorage.app',
    measurementId: 'G-P71CS94566',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16UGAr_omaRkbSt9JuygKi2brkCyg7vI',
    appId: '1:551736633719:android:182e58ea12a26a467c9972',
    messagingSenderId: '551736633719',
    projectId: 'biovolt',
    storageBucket: 'biovolt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXiCfkviqyQM8j4COY8Bf_sARZcn4JFcg',
    appId: '1:551736633719:ios:048db425cfddf2947c9972',
    messagingSenderId: '551736633719',
    projectId: 'biovolt',
    storageBucket: 'biovolt.firebasestorage.app',
    androidClientId: '551736633719-u42iaksv57tet7bm903dob63fs6abdnc.apps.googleusercontent.com',
    iosClientId: '551736633719-0spqjhak0tf5oju7b3f5lh9s2sqgtvcp.apps.googleusercontent.com',
    iosBundleId: 'com.biovolt.biovoltTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXiCfkviqyQM8j4COY8Bf_sARZcn4JFcg',
    appId: '1:551736633719:ios:048db425cfddf2947c9972',
    messagingSenderId: '551736633719',
    projectId: 'biovolt',
    storageBucket: 'biovolt.firebasestorage.app',
    androidClientId: '551736633719-u42iaksv57tet7bm903dob63fs6abdnc.apps.googleusercontent.com',
    iosClientId: '551736633719-0spqjhak0tf5oju7b3f5lh9s2sqgtvcp.apps.googleusercontent.com',
    iosBundleId: 'com.biovolt.biovoltTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ8L4vZX9mGOkmZQEPfnuy3v3c7orXCqM',
    appId: '1:551736633719:web:69fd0631eb5433fa7c9972',
    messagingSenderId: '551736633719',
    projectId: 'biovolt',
    authDomain: 'biovolt.firebaseapp.com',
    storageBucket: 'biovolt.firebasestorage.app',
    measurementId: 'G-G92PJL4SRF',
  );
}
